[package]
name = "smyk07_art"
version = "0.1.0"
edition = "2021"
description = "A library for modelling artistic concepts"
license = "MIT"

[dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
